apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector: # service is going to select a pod where it finds these labels
    name: frontend
    project: expense
    environment: dev
    tier: web
  ports:
    - protocol: TCP # UPPERCASE only
      port: 80 # service-port or clusterIP port
      targetPort: 80 # port of target container/pod(here-->nginx)
  type: ClusterIP   # Exposes the service internally within the pod n/w