apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector: # service is going to select a pod where it finds these labels
    name: frontend
    project: expense
    environment: dev
    tier: web
  ports:
    - protocol: TCP # UPPERCASE only
      port: 80 # service-port or clusterIP port
      targetPort: 80 # port of target container/pod(here-->nginx)
      nodePort: 30001
  type: NodePort   # Exposes the service to internet, listens on a port no. of node/ec2.



# OFFICIAL TEMPLATE FROM K8s

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   type: NodePort
#   selector:
#     app.kubernetes.io/name: MyApp
#   ports:
#     - port: 80
#       # By default and for convenience, the `targetPort` is set to
#       # the same value as the `port` field.
#       targetPort: 80
#       # Optional field
#       # By default and for convenience, the Kubernetes control plane
#       # will allocate a port from a range (default: 30000-32767)
#       nodePort: 30007