apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx # name of replicaset
  labels: # labels are for replicaset resource
    app: nginx
    tier: web
    project: expense
    component: frontend
spec:
  # modify replicas according to your case
  replicas: 3 # we can choose no. of replicas needed
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: expense
      component: frontend
  # below is pod definition
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: expense
        component: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
