apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # deployment related labels
    app: nginx
    tier: web
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: expense
  template: #pod definition
    metadata:
      labels:
        app: nginx
        tier: web
        project: expense
    spec:
      containers:
      - name: nginx
        image: nginx
